#!/bin/sh

opts=$1

cp -a node_modules/uswds/dist/fonts static/

if [ "$opts" == "--watch" ]; then
    set -x
    sass --watch scss/atat.scss:static/assets/atat.css
else
    set -x
    sass scss/atat.scss > static/assets/atat.css
fi

