apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reset-db
  namespace: atat
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: atst
            role: reset-db
            aadpodidbinding: atat-kv-id-binding
        spec:
          restartPolicy: OnFailure
          containers:
          - name: reset
            image: $CONTAINER_IMAGE
            command: [
              "/bin/sh", "-c"
            ]
            args: [
              "/opt/atat/atst/.venv/bin/python",
              "/opt/atat/atst/script/reset_database.py"
            ]
            envFrom:
            - configMapRef:
                name: atst-worker-envvars
            volumeMounts:
              - name: flask-secret
                mountPath: "/config"
          volumes:
            - name: flask-secret
              flexVolume:
                driver: "azure/kv"
                options:
                  usepodidentity: "true"
                  keyvaultname: "atat-vault-test"
                  keyvaultobjectnames: "staging-AZURE-STORAGE-KEY;staging-MAIL-PASSWORD;staging-PGPASSWORD;staging-REDIS-PASSWORD;staging-SECRET-KEY"
                  keyvaultobjectaliases: "AZURE_STORAGE_KEY;MAIL_PASSWORD;PGPASSWORD;REDIS_PASSWORD;SECRET_KEY"
                  keyvaultobjecttypes: "secret;secret;secret;secret;key"
                  tenantid: $TENANT_ID
