"""add status to invitation

Revision ID: 03654d08f5ff
Revises: 2bec1868a22a
Create Date: 2018-10-26 12:59:16.709080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03654d08f5ff'
down_revision = '2bec1868a22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('status', sa.Enum('ACCEPTED', 'REVOKED', 'PENDING', 'REJECTED', name='status', native_enum=False), nullable=True))
    op.drop_column('invitations', 'valid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('invitations', 'status')
    # ### end Alembic commands ###
