"""Add Custom Clauses to Task Order

Revision ID: 0ff4c31c4d28
Revises: da9d1c911a52
Create Date: 2019-01-30 11:28:37.193854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff4c31c4d28'
down_revision = 'da9d1c911a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_orders', 'loa', type_=sa.String(), nullable=True)
    op.add_column('task_orders', sa.Column('custom_clauses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_orders', 'custom_clauses')
    op.alter_column('task_orders', 'loa', type_=sa.ARRAY(sa.String()), nullable=True)
    # ### end Alembic commands ###
