"""add user data fields to invitations

Revision ID: 41e7f810396a
Revises: c5deba1826be
Create Date: 2019-05-28 10:26:30.748332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e7f810396a'
down_revision = 'c5deba1826be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_invitations', sa.Column('dod_id', sa.String(), nullable=True))
    op.add_column('application_invitations', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('application_invitations', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('application_invitations', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('portfolio_invitations', sa.Column('dod_id', sa.String(), nullable=True))
    op.add_column('portfolio_invitations', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('portfolio_invitations', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('portfolio_invitations', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_invitations', 'phone_number')
    op.drop_column('portfolio_invitations', 'last_name')
    op.drop_column('portfolio_invitations', 'first_name')
    op.drop_column('portfolio_invitations', 'dod_id')
    op.drop_column('application_invitations', 'phone_number')
    op.drop_column('application_invitations', 'last_name')
    op.drop_column('application_invitations', 'first_name')
    op.drop_column('application_invitations', 'dod_id')
    # ### end Alembic commands ###
