"""add environment_role status

Revision ID: 4477b211a07c
Revises: e3d93f9caba7
Create Date: 2019-09-20 11:04:10.961311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4477b211a07c' # pragma: allowlist secret
down_revision = 'e3d93f9caba7' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment_roles', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'PENDING_DELETE', name='status', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment_roles', 'status')
    # ### end Alembic commands ###
