"""add funding columns to task order

Revision ID: 4536f50b25bc
Revises: 71cbe76c3b87
Create Date: 2019-01-10 14:24:03.101309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4536f50b25bc'
down_revision = '71cbe76c3b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('attachment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('task_orders', sa.Column('performance_length', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_orders', 'attachments', ['attachment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_orders', type_='foreignkey')
    op.drop_column('task_orders', 'performance_length')
    op.drop_column('task_orders', 'attachment_id')
    # ### end Alembic commands ###
