"""add Environment csp info

Revision ID: 502e79c55d2d
Revises: 4a3122ffe898
Create Date: 2019-09-05 13:54:23.840512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '502e79c55d2d'
down_revision = 'cfab6c8243cb' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('baseline_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('environments', sa.Column('root_user_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'root_user_info')
    op.drop_column('environments', 'baseline_info')
    # ### end Alembic commands ###
