"""remove accepted from workspace_role

Revision ID: 67955a4abaef
Revises: e62bcc460c26
Create Date: 2018-10-26 13:57:29.480236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67955a4abaef'
down_revision = 'e62bcc460c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_roles', 'accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_roles', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
