"""remove baseline_info

Revision ID: 687fd43489d6
Revises: f328f1ea400c
Create Date: 2019-10-30 13:49:55.757825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '687fd43489d6' # pragma: allowlist secret
down_revision = 'f328f1ea400c' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'baseline_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environments', sa.Column('baseline_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
