"""add oversight columns to task order

Revision ID: 7f2040715b0d
Revises: 4536f50b25bc
Create Date: 2019-01-10 16:34:20.185768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2040715b0d'
down_revision = '4536f50b25bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('cor_phone_number', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('ko_phone_number', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('so_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_orders', 'so_phone_number')
    op.drop_column('task_orders', 'ko_phone_number')
    op.drop_column('task_orders', 'cor_phone_number')
    # ### end Alembic commands ###
