"""Add cloud_id column to user

Revision ID: 91bd9482ce23
Revises: b3fa1493e0a9
Create Date: 2019-01-08 10:18:23.764179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bd9482ce23'
down_revision = 'b3fa1493e0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cloud_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cloud_id')
    # ### end Alembic commands ###
