"""make user_id nullable for role models

Revision ID: 92e35177d8b2
Revises: 41e7f810396a
Create Date: 2019-05-28 14:21:02.348264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92e35177d8b2'
down_revision = '41e7f810396a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_roles', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('portfolio_roles', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_roles', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('application_roles', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
