"""Portfolio demographics

Revision ID: 988f8b23fbf6
Revises: 8467440c4ae6
Create Date: 2019-05-31 14:00:31.197803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988f8b23fbf6'
down_revision = '8467440c4ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('app_migration', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('complexity', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('portfolios', sa.Column('complexity_other', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('description', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('dev_team', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('portfolios', sa.Column('dev_team_other', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('native_apps', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('team_experience', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'team_experience')
    op.drop_column('portfolios', 'native_apps')
    op.drop_column('portfolios', 'dev_team_other')
    op.drop_column('portfolios', 'dev_team')
    op.drop_column('portfolios', 'description')
    op.drop_column('portfolios', 'complexity_other')
    op.drop_column('portfolios', 'complexity')
    op.drop_column('portfolios', 'app_migration')
    # ### end Alembic commands ###
