"""status for existing workspace roles

Revision ID: a9d8c6b6221c
Revises: 5284ac1ac77c
Create Date: 2018-10-31 11:08:05.791739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d8c6b6221c'
down_revision = '5284ac1ac77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("UPDATE workspace_roles set status = 'ACTIVE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("UPDATE workspace_roles set status = null")
    # ### end Alembic commands ###
