"""request_reviews non-nullable fields

Revision ID: bc6edccded26
Revises: 7bdb2055d7c7
Create Date: 2018-09-10 10:38:00.107297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6edccded26'
down_revision = '7bdb2055d7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_reviews', 'fname_ccpo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_reviews', 'fname_mao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_reviews', 'lname_ccpo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_reviews', 'lname_mao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_reviews', 'lname_mao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_reviews', 'lname_ccpo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_reviews', 'fname_mao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_reviews', 'fname_ccpo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
