"""add jedi clin type to clin table

Revision ID: c19d6129cca1
Revises: 988f8b23fbf6
Create Date: 2019-06-04 11:30:25.283028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19d6129cca1'
down_revision = '988f8b23fbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clins', sa.Column('jedi_clin_type', sa.Enum('JEDI_CLIN_1', 'JEDI_CLIN_2', 'JEDI_CLIN_3', 'JEDI_CLIN_4', name='jediclintype', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clins', 'jedi_clin_type')
    # ### end Alembic commands ###
