"""add accepted column to workspace role

Revision ID: c7feaa7b6b0c
Revises: 5284ac1ac77c
Create Date: 2018-10-25 11:44:17.654892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7feaa7b6b0c'
down_revision = '5284ac1ac77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_roles', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_roles', 'accepted')
    # ### end Alembic commands ###
