"""record invitation status

Revision ID: c98adf9bb431
Revises: da9d1c911a52
Create Date: 2019-02-06 09:02:28.617202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98adf9bb431'
down_revision = 'da9d1c911a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('cor_invite', sa.Boolean(), nullable=True))
    op.add_column('task_orders', sa.Column('ko_invite', sa.Boolean(), nullable=True))
    op.add_column('task_orders', sa.Column('so_invite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_orders', 'so_invite')
    op.drop_column('task_orders', 'ko_invite')
    op.drop_column('task_orders', 'cor_invite')
    # ### end Alembic commands ###
