"""add additional user fields

Revision ID: c99026ab9918
Revises: 903d7c66ff1d
Create Date: 2018-10-15 11:10:46.073745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99026ab9918'
down_revision = '903d7c66ff1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('citizenship', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_latest_training', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('service_branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'service_branch')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'date_latest_training')
    op.drop_column('users', 'citizenship')
    # ### end Alembic commands ###
