"""Add session_id to users table

Revision ID: d1de95e220c7
Revises: 432c5287256d
Create Date: 2019-05-15 10:34:08.108288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1de95e220c7'
down_revision = '432c5287256d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
