"""remove task_orders.number unique constraint

Revision ID: d966d7194f5c
Revises: 3d3c71b03e98
Create Date: 2019-06-19 12:53:39.502250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd966d7194f5c'
down_revision = '3d3c71b03e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_orders_number_key1', 'task_orders', type_='unique')
    # ### end Alembic commands ###


# Not downgradeable; would have to determine what redundant TOs to delete
