"""Remove status column from task order

Revision ID: da9d1c911a52
Revises: a6837632686c
Create Date: 2019-01-14 11:21:51.729134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9d1c911a52'
down_revision = 'a6837632686c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_orders', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('status', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
