"""add status to workspace_roles

Revision ID: e0fc3cd315c1
Revises: 994a80ee92c9
Create Date: 2018-10-30 14:36:51.047876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fc3cd315c1'
down_revision = '994a80ee92c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_roles', sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'PENDING', name='status', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_roles', 'status')
    # ### end Alembic commands ###
