"""add expiration_time to invitation

Revision ID: e62bcc460c26
Revises: 03654d08f5ff
Create Date: 2018-10-26 13:37:39.015003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62bcc460c26'
down_revision = '03654d08f5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('expiration_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'expiration_time')
    # ### end Alembic commands ###
