"""update task order columns

Revision ID: ea06f5863083
Revises: a4cb6444eb4a
Create Date: 2018-12-14 13:19:11.956511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea06f5863083'
down_revision = 'a4cb6444eb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('app_migration', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('clin_01', sa.Integer(), nullable=True))
    op.add_column('task_orders', sa.Column('clin_02', sa.Integer(), nullable=True))
    op.add_column('task_orders', sa.Column('clin_03', sa.Integer(), nullable=True))
    op.add_column('task_orders', sa.Column('clin_04', sa.Integer(), nullable=True))
    op.add_column('task_orders', sa.Column('complexity', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('task_orders', sa.Column('complexity_other', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('cor_dod_id', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('cor_email', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('cor_first_name', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('cor_last_name', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('defense_component', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('dev_team', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('task_orders', sa.Column('dev_team_other', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('task_orders', sa.Column('ko_dod_id', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('ko_email', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('ko_first_name', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('ko_last_name', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('loa', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('task_orders', sa.Column('native_apps', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('so_dod_id', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('so_email', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('so_first_name', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('so_last_name', sa.String(), nullable=True))
    op.add_column('task_orders', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('task_orders', sa.Column('team_experience', sa.String(), nullable=True))
    op.drop_column('task_orders', 'expiration_date')
    op.drop_column('task_orders', 'clin_1003')
    op.drop_column('task_orders', 'clin_0001')
    op.drop_column('task_orders', 'clin_2003')
    op.drop_column('task_orders', 'clin_1001')
    op.drop_column('task_orders', 'clin_2001')
    op.drop_column('task_orders', 'clin_0003')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_orders', sa.Column('clin_0003', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_orders', sa.Column('clin_2001', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_orders', sa.Column('clin_1001', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_orders', sa.Column('clin_2003', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_orders', sa.Column('clin_0001', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_orders', sa.Column('clin_1003', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_orders', sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('task_orders', 'team_experience')
    op.drop_column('task_orders', 'start_date')
    op.drop_column('task_orders', 'so_last_name')
    op.drop_column('task_orders', 'so_first_name')
    op.drop_column('task_orders', 'so_email')
    op.drop_column('task_orders', 'so_dod_id')
    op.drop_column('task_orders', 'scope')
    op.drop_column('task_orders', 'native_apps')
    op.drop_column('task_orders', 'loa')
    op.drop_column('task_orders', 'ko_last_name')
    op.drop_column('task_orders', 'ko_first_name')
    op.drop_column('task_orders', 'ko_email')
    op.drop_column('task_orders', 'ko_dod_id')
    op.drop_column('task_orders', 'end_date')
    op.drop_column('task_orders', 'dev_team_other')
    op.drop_column('task_orders', 'dev_team')
    op.drop_column('task_orders', 'defense_component')
    op.drop_column('task_orders', 'cor_last_name')
    op.drop_column('task_orders', 'cor_first_name')
    op.drop_column('task_orders', 'cor_email')
    op.drop_column('task_orders', 'cor_dod_id')
    op.drop_column('task_orders', 'complexity_other')
    op.drop_column('task_orders', 'complexity')
    op.drop_column('task_orders', 'clin_04')
    op.drop_column('task_orders', 'clin_03')
    op.drop_column('task_orders', 'clin_02')
    op.drop_column('task_orders', 'clin_01')
    op.drop_column('task_orders', 'app_migration')
    # ### end Alembic commands ###
