"""extended fv

Revision ID: edf509c974f6
Revises: 9c24c609878a
Create Date: 2018-10-19 14:06:45.396974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf509c974f6'
down_revision = '9c24c609878a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_revisions', sa.Column('extended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_revisions', 'extended')
    # ### end Alembic commands ###
