"""Make application description optional

Revision ID: f50596c5ffbb
Revises: e3d93f9caba7
Create Date: 2019-10-08 09:41:11.835664

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f50596c5ffbb"  # pragma: allowlist secret
down_revision = "e3d93f9caba7"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
