#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Install Python dependencies
pipenv --python 3.6
pipenv run pip install --upgrade pip
pipenv install --dev

# Install uswds node module and dependencies
npm install

# Precompile assets for deployment
pipenv run webassets -m atst.assets build
