#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Set sass compiling command for this app
COMPILE_SASS_CMD="webassets -m atst.assets build"

# Enable python and node package installation
INSTALL_PYTHON_PACKAGES="true"
INSTALL_NODE_PACKAGES="true"

# Run the shared bootstrap script
source ./script/include/run_bootstrap

# Link USWDS fonts into the /static directory
rm -f ./static/fonts
ln -s ../node_modules/uswds/src/fonts ./static/fonts
