#!/bin/bash

# script/cibuild: Run CI related checks and tests

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Run lint/style checks and unit tests
script/test

# Run static code analysis security check (exluding the tests subdir)
bandit -r . -x tests
