#!/bin/bash

# script/dev_queue: Run the queue with entr if available

set -e

WORKER="pipenv run celery -A celery_worker.celery worker --loglevel=info"

if [[ `command -v entr` ]]; then
  find atst | entr -r $WORKER
else
  $WORKER
fi
