#!/bin/bash

FILES_TO_FORMAT="atst/ tests/ app.py script/"

if [ "$1" == "check" ]; then
  pipenv run black --check ${FILES_TO_FORMAT}
  yarn run prettier --list-different "js/**/*.js" --config ./prettier.config.json
  yarn run prettier --list-different "styles/**/*.scss"
else
  pipenv run black ${FILES_TO_FORMAT}
  yarn run prettier --list-different --write "js/**/*.js" --config ./prettier.config.json
  tt
  yarn run prettier --list-different --write "styles/**/*.scss"
fi
