#!/bin/bash

# script/rq_worker: Launch the Flask-RQ worker

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Before starting the server, apply any pending migrations to the DB
migrate_db

# Launch the worker
run_command "flask rq worker"
