#!/bin/bash

reap() {
   kill -TERM $child
   sleep 0.1
   exit
}

trap reap TERM INT

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Launch the app
pipenv run python app.py ${@} &
child=$!

wait $child
