#!/bin/bash

# script/server: Launch the server

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Compile js/css assets
yarn build

# Launch the app
run_command "./app.py ${LAUNCH_ARGS}"
