#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Turn on sass compiler installation
INSTALL_SASS="true"

# Set database name
DATABASE_NAME="atat"

# Enable database resetting
RESET_DB="true"

# Run the shared setup script
source ./script/include/run_setup

# Fetch and import the PE numbers
run_command "python script/ingest_pe_numbers.py"
