#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Turn on sass compiler installation
INSTALL_SASS="true"

# Run the shared setup script
source ./script/include/run_setup
