#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Install virtualenv
pip install pipenv

# Update npm
npm install -g npm

if ! type sass > /dev/null; then
  if type gem > /dev/null; then
    echo 'installing a sass compiler...'
    gem install sass
  else
    echo 'Could not install a sass compiler. Please install a version of sass.'
  fi
fi

# Install application dependencies
script/bootstrap

# Generate default configuration
script/config

# Symlink uswds fonts into the /static directory
ln -s ../node_modules/uswds/src/fonts ./static/fonts
