#!/bin/bash

# script/test: Run static code checks and unit tests

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

export FLASK_ENV=test

# Define all relevant python files and directories for this app
PYTHON_FILES="./app.py ./atst ./config"

# Enable Python testing
RUN_PYTHON_TESTS="true"

# Run the shared test script
source ./script/include/run_test
