#!/bin/bash

# If a command fails, exit the script
set -e

# Ensure we are in the app root directory (not the /script directory)
cd "$(dirname "${0}")/.."

# Activate virtual environment
source .venv/bin/activate

# Run unit tests
python3 -m pytest
