#!/bin/bash

# script/update: Update dependencies

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Enable DB migration
MIGRATE_DB="true"

# Run the shared update script
source ./script/include/run_update
