#!/bin/bash

# script/update: Update dependencies

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# create upload directory for app
mkdir uploads | true

# Enable DB migration
MIGRATE_DB="true"

# Run the shared update script
source ./script/include/run_update

# Fetch and import/update the PE numbers
run_command "python script/ingest_pe_numbers.py"
